### ISSUE TITLE
Faceplate - Standard - Rear - Low.stl

### ISSUE THREAD

**Issue by YesterdaysCoffee** [Armchair-Heavy-Industries/Xol-Toolhead#24] opened 2024-01-11 23:26 UTC
holes for fan screws are .5mm off center

**Comment by DW-Tas** [comment] 2024-01-18 05:41
Could you please add some more details? the rear faceplate has holes for hotend fan screws, and for the blower fan screws/heat sets.
Images would help if you can provide them here as well.
Thanks.

**Comment by YesterdaysCoffee** [comment] 2024-01-18 16:27
When the rear face plate is mounted with the blower fan screws, all HE fan screws do not line up.  And visa versa, when the rear face plate is mounted with the HE fan screws, all part blower fan screws do not line up.
My workaround was to enlarge the HE fan screw holes.

**Comment by DW-Tas** [comment] 2024-01-19 22:43
I can't reproduce the issue. Everything is lined up in the CAD. 
![image](https://github.com/Armchair-Engineering/Xol-Toolhead/assets/116466447/06ef01f1-78bd-4ebd-8b61-59d6af47930c)

**Comment by DW-Tas** [comment] 2024-03-08 22:59
No reply, closing

**Closed** 2024-03-08 22:59 UTC
